Repository GlobalNomads/TripNomadHub, pull requests merged in 2024-07, with the labels that each got.

#1 Feat: 체험상세 페이지 제목 UI
  app/activities/_components/ActivityTitle.tsx
  app/activities/page.tsx
Labels: ✨ feat

#2 feat: MockData 연결
  app/activities/_components/ActivityTitle.tsx
  app/activities/page.tsx
Labels: ✨ feat

#4 feat: 체험 상세 페이지 갤러리 추가
  .vscode/settings.json
  app/activities/_components/ActivityImageGallery.tsx
  app/activities/_components/ActivityTitle.tsx
  app/activities/_components/SwiperContainer.tsx
  app/activities/_components/swiper.d.ts
  app/activities/page.tsx
  app/styles/globals.css
  package-lock.json
  package.json
Labels: ✨ feat

#3 feat: Footer UI
  app/assets/icon/FacebookIcon.tsx
  app/assets/icon/InstagramIcon.tsx
  app/assets/icon/TwitterIcon.tsx
  app/assets/icon/YoutubeIcon.tsx
  app/components/Footer/Footer.tsx
  app/components/Footer/FooterLink.tsx
  app/page.tsx
Labels: ✨ feat

#6 feat: 로그인 화면 기본 구조 작업
  app/signin/page.tsx
Labels: ✨ feat

#8 feat: 회원가입 기본 ui 작업
  app/signup/page.tsx
Labels: ✨ feat

#7 feat: 로그인 ul 추가 css 기본 디자인 완성
  app/signin/page.tsx
Labels: ✨ feat

#5 feat: 사이드 네비 카드
  .prettierrc.js
  app/assets/icon/ic_calendar.svg
  app/assets/icon/ic_gray_account_check_outline.svg
  app/assets/icon/ic_gray_calender.svg
  app/assets/icon/ic_gray_cog.svg
  app/assets/icon/ic_gray_text_box_check_outline.svg
  app/assets/icon/ic_pencil.svg
  app/favicon.ico
  app/layout.tsx
  app/myreservations/_components/ButtonWithHover.tsx
  app/myreservations/_components/ProfileImage.tsx
  app/myreservations/_components/ReservationCard.tsx
  app/myreservations/_components/SideNavCard.tsx
  app/myreservations/page.tsx
  package-lock.json
  package.json
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  tailwind.config.ts
Labels: ✨ feat

#9 feat: 드롭다운 컴포넌트 & 체험상세 페이지 드롭다운 메뉴(케밥버튼) 생성
  app/activities/_components/DropDownMenu.tsx
  app/activities/_components/SwiperContainer.tsx
  app/activities/page.tsx
  app/components/DropDown/DropDown.tsx
Labels: ✨ feat

#10 feat: 폰트 설정 & 버튼 컴포넌트 개발
  app/assets/fonts/PretendardStdVariable.woff2
  app/assets/icon/ic_filter_arrow.svg
  app/components/Button/Button.tsx
  app/components/Button/CategoryButton.tsx
  app/components/Button/DefaultButton.tsx
  app/components/Button/FilterButton.tsx
  app/components/Button/LoginButton.tsx
  app/components/Button/ModalButton.tsx
  app/components/Button/SearchButton.tsx
  app/components/Button/page.tsx
  app/layout.tsx
  app/styles/globals.css
  tailwind.config.ts
Labels: ✨ feat

#13 feat: 로그인 submit form 완성
  app/(auth)/signin/_components/ErrorText.tsx
  app/(auth)/signin/_components/Input.tsx
  app/(auth)/signin/_components/Label.tsx
  app/(auth)/signin/_components/SigninForm.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/signin/page.tsx
  package-lock.json
  package.json
Labels: ✨ feat

#14 feat: 회원가입 submit form 완성
  app/(auth)/_components/ErrorText.tsx
  app/(auth)/_components/Input.tsx
  app/(auth)/_components/Label.tsx
  app/(auth)/_components/SigninForm.tsx
  app/(auth)/_components/SignupForm.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/activities/_components/ActivityTitle.tsx
  app/activities/_components/DropDownMenu.tsx
  app/components/Button/FilterButton.tsx
  app/components/Footer/Footer.tsx
  app/myreservations/_components/SideNavCard.tsx
  tsconfig.json
Labels: ✨ feat

#11 doc: Readme.md 초안
  README.md
Labels: 📝 doc

#16 feat: 단축경로 추가 및 전 파일 경로 수정
  app/(auth)/_components/SigninForm.tsx
  app/(auth)/_components/SignupForm.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/activities/_components/ActivityTitle.tsx
  app/activities/_components/DropDownMenu.tsx
  app/components/Button/FilterButton.tsx
  app/components/Footer/Footer.tsx
  app/components/Modal/CancelModal.tsx
  app/components/Modal/ConfirmModal.tsx
  app/components/Modal/DefaultModal.tsx
  app/components/Modal/ReviewModal.tsx
  app/components/Modal/page.tsx
  app/myreservations/_components/SideNavCard.tsx
  tsconfig.json
Labels: ✨ feat

#17 refactor: 체험 상세 페이지 수정 요청 사항 반영
  .gitignore
  app/activities/_components/ActivityImageGallery.tsx
  app/activities/_components/DropDownMenu.tsx
  app/components/DropDown/DropDown.tsx
  app/layout.tsx
  next.config.mjs
Labels: 🔧 refactor

#19 feat: 체험 상세 페이지 체험 설명 완성
  app/activities/_components/ActivityDescription.tsx
  app/activities/_components/ActivityImageGallery.tsx
  app/activities/page.tsx
Labels: ✨ feat
